### ISSUE TITLE
Twitterの文字数制限が考慮されていない

### ISSUE THREAD

**Issue by Yz4230** [Yz4230/HP_monitor#7]
現在のコードではTwitterには文字数制限があることが考慮されていません。140文字を超えたら本文の末尾に「...」をつけることで対応しようと思っています。

**Comment by Yz4230** [comment]
「…」でいいですか。

**Comment by dm2422** [comment]
めーるみてなかったです。すみません

**Comment by dm2422** [comment]
Looks Good To Me

**Comment by Yz4230** [comment]
#8 をマージしたので、解決済みとします。
